development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: desconto_inss_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: desconto_inss_production
